### ISSUE TITLE
Cannot build agent part of snap from agent/dev

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/snap#13]
In build process, snapcraft downloading dependencies for go products via `go get`.
in this case, if we trying build agent from dev branch, `go get` will be download agent repo from master branch (to resolve in code dependencies).

it is related to import currently implemented import method - by using links to github.

**Comment by soffokl** [comment]
Fixed here: https://github.com/subutai-io/agent/commit/e2b5cd8f9a22b8e9a4809bf63fae9cfb23509549
