### ISSUE TITLE
Improper shutdown leads to umount errors on shutdown

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/snap#177]
The services are certainly not being shutdown properly and are left hanging holding onto file descriptors on file systems that are being umounted during shutdown. It then takes a while for timeouts and hence the shutdown sequence is taking 3-4 minutes. Here's what it looks like on a Debian stretch VM:

![debian-stretch](https://user-images.githubusercontent.com/10051386/34227395-2834fa46-e5f7-11e7-8ff9-b98ec0f8f242.png)

We get the same problems on Ubuntu Xenial however the timeouts are not causing this much delay.

**Comment by happyaron** [comment]
I think this is probably the same as #224, due to the fact that we are not stopping all containers during shutdown. There might be dangling writes happening to prevent umount or breaking the file system.

**Comment by Dilshat** [comment]
Related https://github.com/subutai-io/agent/issues/270

**Comment by AlinaPenkina** [comment]
We tested on Ubuntu/xenial and it still shows error-failed unmounting /var.

**Comment by amol4anoff** [comment]
I updated peer, then rebooted peer and caught error - Failed unmounting /var.
