### ISSUE TITLE
Can not remove snap after installation

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#212]
Snap removal does not work once subutai snap is installed.
It can be deactivated but not removed.
Probably some services are not properly shut down and still holding resource locks.
Need to investigate the reasons and possibly fix the problem.

**Comment by happyaron** [comment]
Suspect it's about some file descriptors might not be closed properly in containers, need to find out if that's the case.

**Comment by liquuid** [comment]
I managed remove subutai snap after `umount /var/snap/subutai/common/lxc`. The Strange part, i can't remove subutai snap even without have any container installed.

**Comment by Dilshat** [comment]
Great, thanks for investigation, I will test and report if anything else pops up

**Comment by lbthomsen** [comment]
I can second that unmounting /var/snap/subutai/common/lxc before doing the ```snap remove subutai``` works, but this one might go a little deeper than this because even when doing that - the actual block device used for the btrfs is still busy and can not be reused.

**Comment by Dilshat** [comment]
@lbthomsen any suggestion on how to work this around?

**Comment by happyaron** [comment]
@Dilshat If we can reliably kill all containers before stopping the service (which is required when shutting down and removal), then umounting would be able to release the block device, so these are related issues.

**Comment by Dilshat** [comment]
Great thanks for clarifying the matter
