### ISSUE TITLE
Management container did not automatically start on restart

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/snap#215]
This issue is connected to this one: https://github.com/subutai-io/agent/issues/254. The VM that failed in this issue was restarted and did not have the management container come up. It had to be manually restarted. @Shahrizada please use this issue and the other one if you notice problems today with testing. 

**NOTE**: I would count this peer are crippled and not suitable for clean room testing. It could have numerous problems after this incident.

**Comment by Dilshat** [comment]
@akarasulu please test on latest peer if this issue is reproduced

**Comment by akarasulu** [comment]
Again as with the related  subutai-io/agent#254 issue, I think we should close this issue for now and reopen if it reoccurs. The peer in question had some unusual issues that were never before seen.
