### ISSUE TITLE
Detect unclean shutdown

### ISSUE THREAD

**Issue by happyaron** [subutai-io/snap#232]
Detect unclean shutdown is required for the 3-step of defensive actions for the btrfs failure issue (#229), so that we are able to run the costy `btrfs scrub` when an unclean shutdown is detected, apart from a regularly scheduled scrub that has a long interval.

**Comment by Dilshat** [comment]
also this command can be run to decrease space allocated by btrfs for metadata
`btrfs balance start -m /mountpoint`
