### ISSUE TITLE
Figure out if we can safely update snap via daemon

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#247]
User can safely update snap via `subutai update rh` cli command.
Need to investigate if subutai daemon can do the same and without side effects

**Comment by Dilshat** [comment]
https://superuser.com/questions/178587/how-do-i-detach-a-process-from-terminal-entirely

**Comment by Dilshat** [comment]
We can update via Console however we will not get response about completion from agent because agent gets stopped and restarted upon snap update.
More sage way would be to issue this command `subutai update rh & disown` in a daemon mode and not wait for completion. Probably we can assume that update has been made if agent send heartbeat which it does on being started

**Comment by amol4anoff** [comment]
subutai update rh & disown - this command works in console
