### ISSUE TITLE
Amazon Route 53 domain names not reachable from inside a container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#249]
In some cases, one can not reach to Amazon Route 53 domain names from inside a management container (probably others too). Namely *cdn.subut.ai, *hub.subut.ai etc.
At the same time other domains are reachable (both http and https).
And you **can** reach the Route 53 domains from the Resource Host where these containers are running.

**Comment by lbthomsen** [comment]
First step - need to break down if this is a DNS issue or a connection issue.

**Comment by Dilshat** [comment]
By @lbthomsen :
temporary workaround until we figure out the exact cause - inside management: "ip link set dev eth0 mtu 1300"

**Comment by Dilshat** [comment]
The issue is solved on server side
