### ISSUE TITLE
Filesystem on peer becomes read-only

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#289]
For some reason on peers , btrfs mount can get read-only
So far we noticed this on VirtualBox based peers.
```
root@subutai:~# mount | grep btrfs
/dev/mapper/main-btrfs on /var/snap/subutai-master/common/lxc type btrfs (ro,relatime,space_cache,subvolid=5,subvol=/)
```
and the following log:
``[146351.455911] BTRFS error (device dm-6): parent transid verify failed on 187531264 wanted 1503 found 10532`

**Comment by etursunbaev** [comment]
moved to ZFS, not actual
