### ISSUE TITLE
Static network configuration for peers

### ISSUE THREAD

**Issue by soffokl** [subutai-io/snap#41]
@akarasulu commented on [Wed Jan 11 2017](https://github.com/subutai-io/subos/issues/635)

I know we've make the configuration of the peer dynamic and even made it so we can gracefully handle roaming. However in a server installation no one wants to deal with DHCP. Administrators will want to configure peers and resource hosts statically. We need to provide an option for this.

For the short term a just a simple how to guide to setup static networking and stop the initbr script might be the enough for the peer/rh wan interface.

**Comment by tzununbekov** [comment]
Need to find the friendly way to disable roaming service

**Comment by Dilshat** [comment]
Lets think of how we can make this
