### ISSUE TITLE
Shouldn't root@IP really be subutai@ip?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/snap#50]
When using the autobuild.sh script it worked properly but I got the following message.

> Waiting for Subutai IP address
> *******
> Please use following command to access your resource host:
> ssh root@192.168.81.251
> or login "subutai" with password "ubuntai"
> *******

User root does not seem to work with password `ubuntai`. Am I doing something wrong here?

**Comment by tzununbekov** [comment]
@akarasulu Autobuild script installs user ssh key into RH root account. If, for some reason, user cannot authorize with his key under root account, he should use `subutai` user with password authorization. I'll update script output if it's not clear now
