### ISSUE TITLE
Investigate the option to run Subutai peer on different hypervisors

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/snap#54]
Jon keeps telling us our main target is the System Administrator. We focused on the babushka users and did not create any PROPER documentation for technically capable people who want to install on a headless system for example. We need to provide installation instructions for: 

-  Peers: KVM, Bare Metal, Hyper-V, VMWare
- Headed Peers: VirtualBox, VMWare, KVM
- P2P access only (headed and not headed) (need packages)
- Headed Desktop access: Tray, E2E and P2P Daemon

We already have some started here in the Subos Wiki. We need to brush it up, finish it up, and make sure it all works with the new Ubuntu Core 16 and 5.0 release.

See note with link to old wiki's documents.

**Comment by akarasulu** [comment]
It is possible I did this several times myself.

**Comment by akarasulu** [comment]
See the documents that I had created before we migrated to core 16 with the 5.0 release: 

[Wiki - Alternative Installations](https://github.com/subutai-io/subos/wiki/Alternative-Installations)
