### ISSUE TITLE
CLI hang on cmd `subutai list -i`

### ISSUE THREAD

**Issue by absidish** [subutai-io/snap#69]
1) Created fresh peer 6.1.0
2) Registered to HUB
3) After 40 min `subutai list -i ` is  hang 

![screenshot from 2017-10-11 16-58-15](https://user-images.githubusercontent.com/8696139/31437856-915b6112-aea8-11e7-8610-d70f1f75e0d3.png)

**Comment by Dilshat** [comment]
@absidish please check if this issue still persists

**Comment by absidish** [comment]
couldn`t reproduce
