### ISSUE TITLE
Upload Appscale app failed with  code 413 "Request Entity Too Large"

### ISSUE THREAD

**Issue by absidish** [subutai-io/snap#70]
It was java application  22.4MB
![screenshot from 2017-10-13 10-05-10](https://user-images.githubusercontent.com/8696139/31530065-6b825ea2-afff-11e7-8301-b6e6366445db.png)

**Comment by soffokl** [comment]
@absidish Should be fixed now. Could you check it?

**Comment by absidish** [comment]
![screenshot from 2017-10-25 11-16-10](https://user-images.githubusercontent.com/8696139/31981561-ff868bb2-b975-11e7-937a-a932adda9280.png)
still geting same  error

**Comment by absidish** [comment]
it was nginx inside  container. closing issue
