### ISSUE TITLE
Management Console is unreachable after update RH

### ISSUE THREAD

**Issue by absidish** [subutai-io/snap#74]
Created two peers day ago from dev branch.
After update RH via `sudo subutai update rh` Management Console is unreachable.

**Comment by soffokl** [comment]
There is another Java process running outside container
![image](https://user-images.githubusercontent.com/8612618/31657492-52cd06ba-b350-11e7-86c5-320fb25491a4.png)
It looks like there are 2 management containers running
![image](https://user-images.githubusercontent.com/8612618/31657545-74e94ec0-b350-11e7-9aae-bbd66c5e2976.png)
but one was abandoned

**Comment by soffokl** [comment]
@absidish Do you run RH update via SSH manually or using some scripts or subsystems?

**Comment by absidish** [comment]
via SSH manually

**Comment by soffokl** [comment]
fixed
