### ISSUE TITLE
Wrong IP address detection in peer 

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/snap#79]
I have two peers in LAN, after I rebooted wi-fi router, both IP addresses changed. But in Subutai Console of peer their IP addresses is now wrong. They show
`https://10.0.3.15:8443/` and `https://10.0.3.15:8443/`, while in fact real LAN IPs are `192.168.0.111` and `192.168.0.104` respectively.
Because of this issue, cross peer registration not works, I can't approve request.

**Comment by soffokl** [comment]
fixed here https://github.com/subutai-io/snap/commit/3f0a07c5d7e153dfdd3e241fefaa8b98f4167049
