### ISSUE TITLE
Ship certbot with snap

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#87]
We need to ship [certbot ](https://github.com/certbot/certbot) with our snap to use it for certificate generations

**Comment by akarasulu** [comment]
## External Slack Discussion

Question was: Which to prefer: 1. Build from cloned source, 2. Use the owners deb file direct or 3. Let Ubuntu handle via PPA.

We chose 2 because we do not want version to change and it's easier than 1. 3 violates that because ppa might change under our feet.

**Comment by lbthomsen** [comment]
I might have been a tad quick on that one though.  According to this: https://certbot.eff.org/docs/install.html:

"Unless you have very specific requirements, we kindly suggest that you use the Certbot packages provided by your package manager (see certbot.eff.org). If such packages are not available, we recommend using certbot-auto, which automates the process of installing Certbot on your system."

I am going to have a look at that script.

**Comment by etursunbaev** [comment]
it is done in https://github.com/subutai-io/agent/issues/809
Closing
