### ISSUE TITLE
After update of RH , read-only file system prevents further operation of peer

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#89]
Intermittently a problem with the file system being mounted as read-only occurs after an RH update.
This breaks the operation of a peer

**Comment by lbthomsen** [comment]
This one bugs (pun intended) me no end.  It is so intermittent that it is really hard to track down and once it happens the btrfs gets trashed so bad that I have not found a way to recover.  I have so far found no way to provoke it happening.

**Comment by Dilshat** [comment]
Probably it is related to this https://github.com/subutai-io/agent/issues/270

**Comment by AlinaPenkina** [comment]
We weren't able to catch the problem as well.
