### ISSUE TITLE
Make p2p service to be restared on any case

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/snap#91]
Currently p2p service is restarted by systemd only on failure but p2p daemon should not exit at all
so we need to change restart condition to 'always'
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

**Comment by lbthomsen** [comment]
That can be set in snapcraft.yaml: 

restart-condition (string) Condition to restart the daemon under. Valid values are on-failure, on-success, on-abnormal, on-abort, always and never. Defaults to on-failure. See the systemd.service manual on Restart for details.

Trying:

p2p-service:
                command: bin/p2p daemon -save $SNAP_DATA/p2p.save -syslog 127.0.0
                daemon: simple
                restart-condition: always
