### ISSUE TITLE
After snap update p2p systemd unit file has disappeared

### ISSUE THREAD

**Issue by crioto** [subutai-io/snap#92]
We did a `subutai update rh` command and after update found that `snap.subutai.p2p-service.service` was gone. 
Can't provide steps to reproduce now, because this happens really rarely (once per 10-15 updates), but peer itself was operational and no manipulations were made to system prior to update.

**Comment by akarasulu** [comment]
Also I am finding that `systemd restart p2p.service` on client configuration and even in the peer configuration with `systemd restart snap.subutai-p2p.service` is not restarting the daemon. I suspect we have some serious snap configuration problems especially when updates are performed.

**Comment by Dilshat** [comment]
@crioto please close if does not reproduce
